Repository SOPT-all/35-COLLABORATION-WEB-LOTTE_CINEMA, pull requests merged in 2024-11, with the labels that each got.

#9 [Init] style 관련 초기 세팅
  Lotte-Cinema/index.html
  Lotte-Cinema/package.json
  Lotte-Cinema/src/main.tsx
  Lotte-Cinema/src/styles/colors.ts
  Lotte-Cinema/src/styles/emotion.d.ts
  Lotte-Cinema/src/styles/global.ts
  Lotte-Cinema/src/styles/index.ts
  Lotte-Cinema/src/styles/reset.ts
  Lotte-Cinema/src/styles/typographies.ts
  Lotte-Cinema/yarn.lock
Labels: ⚙️ Setting

#11 [Init] svgr 초기 세팅
  Lotte-Cinema/package.json
  Lotte-Cinema/public/svg/.gitkeep
  Lotte-Cinema/src/assets/custom.d.ts
  Lotte-Cinema/src/assets/svg/.gitkeep
  Lotte-Cinema/src/vite-env.d.ts
  Lotte-Cinema/tsconfig.app.json
  Lotte-Cinema/vite.config.ts
  Lotte-Cinema/yarn.lock
Labels: ⚙️ Setting

#12 [Init] react-router-dom 세팅
  Lotte-Cinema/package.json
  Lotte-Cinema/src/App.tsx
  Lotte-Cinema/src/pages/.gitkeep
  Lotte-Cinema/src/pages/InfoCheck/InfoCheck.tsx
  Lotte-Cinema/src/pages/MainPage/MainPage.tsx
  Lotte-Cinema/src/pages/SeatReservation/SeatReservation.tsx
  Lotte-Cinema/src/pages/TheaterList/TheaterList.tsx
  Lotte-Cinema/src/pages/TimeSelect/TimeSelect.tsx
  Lotte-Cinema/src/pages/index.ts
  Lotte-Cinema/src/routes/.gitkeep
  Lotte-Cinema/src/routes/index.tsx
  Lotte-Cinema/src/types/.gitkeep
  Lotte-Cinema/src/types/routeType.ts
  Lotte-Cinema/yarn.lock
Labels: ⚙️ Setting

#14 [Fix] 린트, 포맷팅 오류 수정
  Lotte-Cinema/.eslintrc.cjs
  Lotte-Cinema/.prettierrc
  Lotte-Cinema/.stylelintrc.json
  Lotte-Cinema/eslint.config.js
  Lotte-Cinema/package.json
  Lotte-Cinema/src/App.tsx
  Lotte-Cinema/src/styles/colors.ts
  Lotte-Cinema/src/styles/emotion.d.ts
  Lotte-Cinema/src/styles/global.ts
  Lotte-Cinema/src/styles/index.ts
  Lotte-Cinema/src/styles/reset.ts
  Lotte-Cinema/src/styles/typographies.ts
  Lotte-Cinema/tsconfig.json
  Lotte-Cinema/vite.config.ts
  Lotte-Cinema/yarn.lock
Labels: ⚙️ Setting, 🔧 Fix

#10 [Init] axios instance 생성 및 리액트 쿼리 초기 세팅
  Lotte-Cinema/package.json
  Lotte-Cinema/src/apis/axiosInstance.ts
  Lotte-Cinema/src/hooks/.gitkeep
  Lotte-Cinema/src/hooks/query/.gitkeep
  Lotte-Cinema/src/hooks/queryClient.ts
  Lotte-Cinema/src/main.tsx
  Lotte-Cinema/yarn.lock
Labels: ⚙️ Setting

#16 [Design] 모바일 레이아웃, 헤더 공통 컴포넌트 구현
  Lotte-Cinema/.prettierrc
  Lotte-Cinema/public/svg/.gitkeep
  Lotte-Cinema/public/svg/ic_arrow_left_black_24.svg
  Lotte-Cinema/public/svg/ic_home_black_24.svg
  Lotte-Cinema/src/assets/custom.d.ts
  Lotte-Cinema/src/assets/svg/.gitkeep
  Lotte-Cinema/src/assets/svg/IcArrowLeftBlack24.tsx
  Lotte-Cinema/src/assets/svg/IcHomeBlack24.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/commons/.gitkeep
  Lotte-Cinema/src/components/commons/header/Header.tsx
  Lotte-Cinema/src/components/mobileLayout/MobileLayout.tsx
  Lotte-Cinema/src/pages/InfoCheck/InfoCheck.tsx
  Lotte-Cinema/src/pages/MainPage/MainPage.tsx
  Lotte-Cinema/src/pages/SeatReservation/SeatReservation.tsx
  Lotte-Cinema/src/pages/TheaterList/TheaterList.tsx
  Lotte-Cinema/src/pages/TimeSelect/TimeSelect.tsx
  Lotte-Cinema/src/styles/index.ts
Labels: 🎨 Design

#21 [Fix] svgr 라이브러리 prettier 충돌 문제 해결
  Lotte-Cinema/package.json
Labels: 🔧 Fix

#28 [Design] 메인화면 헤더 컴포넌트 구현 (메인화면 뷰)
  Lotte-Cinema/public/svg/ic_ticket__black_32.svg
  Lotte-Cinema/public/svg/img_logo.svg
  Lotte-Cinema/src/assets/svg/IcTicketBlack32.tsx
  Lotte-Cinema/src/assets/svg/ImgLogo.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/commons/header/Header.tsx
  Lotte-Cinema/src/components/mainPage/MainPageHeader.tsx
  Lotte-Cinema/src/pages/MainPage/MainPage.tsx
Labels: 🎨 Design

#34 [Design] 버튼&모달 컴포넌트 구현 완료 (좌석 선택 뷰)
  Lotte-Cinema/public/svg/img_lpay_logo.svg
  Lotte-Cinema/public/svg/img_payment_complete.svg
  Lotte-Cinema/src/App.tsx
  Lotte-Cinema/src/assets/svg/IcArrowLeftBlack24.tsx
  Lotte-Cinema/src/assets/svg/IcHomeBlack24.tsx
  Lotte-Cinema/src/assets/svg/IcLpayLogo.tsx
  Lotte-Cinema/src/assets/svg/IcPaymentComplete.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/commons/header/Header.tsx
  Lotte-Cinema/src/components/mobileLayout/MobileLayout.tsx
  Lotte-Cinema/src/components/seatReservation/Button.tsx
  Lotte-Cinema/src/components/seatReservation/ModalContents.tsx
  Lotte-Cinema/src/components/seatReservation/ModalWrapper.tsx
  Lotte-Cinema/src/pages/MainPage/MainPage.tsx
  Lotte-Cinema/src/routes/index.tsx
  Lotte-Cinema/src/styles/colors.ts
  Lotte-Cinema/src/styles/emotion.d.ts
  Lotte-Cinema/src/styles/global.ts
  Lotte-Cinema/src/styles/index.ts
  Lotte-Cinema/src/styles/reset.ts
  Lotte-Cinema/src/styles/typographies.ts
Labels: 🎨 Design, 한서

#33 [Design] 영화/영화관 선택 컴포넌트 (시간 선택 뷰)
  Lotte-Cinema/public/svg/ic_age_12_16.svg
  Lotte-Cinema/public/svg/ic_age_19_16.svg
  Lotte-Cinema/public/svg/ic_age_all_16.svg
  Lotte-Cinema/public/svg/ic_arrow_right_white_10.svg
  Lotte-Cinema/public/svg/ic_close_gray14_14.svg
  Lotte-Cinema/src/assets/img/Img4m44s.png
  Lotte-Cinema/src/assets/img/ImgAmazonhms.png
  Lotte-Cinema/src/assets/img/ImgDeadline.png
  Lotte-Cinema/src/assets/img/ImgGladiator.png
  Lotte-Cinema/src/assets/img/ImgHoshimachi.png
  Lotte-Cinema/src/assets/img/ImgKiminonamaewa.png
  Lotte-Cinema/src/assets/img/ImgSummerwars.png
  Lotte-Cinema/src/assets/svg/IcAge1216.tsx
  Lotte-Cinema/src/assets/svg/IcAge1916.tsx
  Lotte-Cinema/src/assets/svg/IcAgeAll16.tsx
  Lotte-Cinema/src/assets/svg/IcArrowRightWhite10.tsx
  Lotte-Cinema/src/assets/svg/IcCloseGray1414.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/commons/ArrowBtn.tsx
  Lotte-Cinema/src/components/commons/header/Header.tsx
  Lotte-Cinema/src/components/timeSelect/MovieInfoBar.tsx
  Lotte-Cinema/src/components/timeSelect/atom/TheaterLabel.tsx
  Lotte-Cinema/src/pages/TimeSelect/TimeSelect.tsx
  Lotte-Cinema/src/utils/index.ts
  Lotte-Cinema/src/utils/runningTimeFormat.ts
Labels: 🎨 Design, 고은

#41 [CICD] yml 작성 후 깃헙 액션 돌려보기
  .DS_Store
  .github/.DS_Store
  .github/workflows/auto.yml
Labels: CICD 🛞

#43 [Fix] 빌드경로 수정
  .github/workflows/auto.yml
Labels: CICD 🛞

#44 [Fix] ever used 변수 삭제
  Lotte-Cinema/src/assets/svg/IcAge1216.tsx
  Lotte-Cinema/src/assets/svg/IcAge1916.tsx
  Lotte-Cinema/src/assets/svg/IcAgeAll16.tsx
  Lotte-Cinema/src/assets/svg/IcArrowRightWhite10.tsx
  Lotte-Cinema/src/assets/svg/IcCloseGray1414.tsx
Labels: CICD 🛞

#46 [Fix] 시크릿 토큰 수정
  .github/workflows/auto.yml
Labels: CICD 🛞

#52 [Fix] token 영역 추가 및 pr 시 빌드
  .github/workflows/auto.yml
Labels: CICD 🛞

#39 [Design] 영화 정보 배너 UI 구현 (정보 확인 및 인원 선택 뷰)
  Lotte-Cinema/public/svg/img_poster_small_amazonhms.svg
  Lotte-Cinema/src/assets/svg/ImgPosterSmallAmazonhms.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/InfoCheck/MovieInfoBanner.tsx
  Lotte-Cinema/src/pages/InfoCheck/InfoCheck.tsx
Labels: 🎨 Design, 진혁

#35 [Design] 영화관 선택 페이지 UI 구현 (영화관 선택 뷰)
  Lotte-Cinema/public/svg/ic_close_gray_temp.svg
  Lotte-Cinema/src/assets/svg/IcCloseGrayTemp.tsx
  Lotte-Cinema/src/assets/svg/ImgPosterSmallAmazonhms.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/TheaterList/List.tsx
  Lotte-Cinema/src/components/TheaterList/Pin.tsx
  Lotte-Cinema/src/components/TheaterList/SelectActions.tsx
  Lotte-Cinema/src/components/TheaterList/SelectButton.tsx
  Lotte-Cinema/src/components/TheaterList/TabBar.tsx
  Lotte-Cinema/src/constants/.gitkeep
  Lotte-Cinema/src/constants/index.ts
  Lotte-Cinema/src/constants/mocks/theaterRegion.ts
  Lotte-Cinema/src/constants/tabs.ts
  Lotte-Cinema/src/pages/TheaterList/TheaterList.tsx
Labels: 🎨 Design, 진혁

#54 [Design] 좌석 선택 뷰 하단 구현
  Lotte-Cinema/public/svg/btn_xsmall.svg
  Lotte-Cinema/public/svg/ic_entrance_10.svg
  Lotte-Cinema/public/svg/ic_seat_disabled_10.svg
  Lotte-Cinema/public/svg/ic_seat_recliner_10.svg
  Lotte-Cinema/src/assets/svg/BtnXsmall.tsx
  Lotte-Cinema/src/assets/svg/IcEntrance10.tsx
  Lotte-Cinema/src/assets/svg/IcSeatDisabled10.tsx
  Lotte-Cinema/src/assets/svg/IcSeatRecliner10.tsx
  Lotte-Cinema/src/assets/svg/ImgLpayLogo.tsx
  Lotte-Cinema/src/assets/svg/ImgPaymentComplete.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/commons/header/Header.tsx
  Lotte-Cinema/src/components/seatReservation/Button.tsx
  Lotte-Cinema/src/components/seatReservation/SeatReserveInfo.tsx
  Lotte-Cinema/src/components/seatReservation/SeatReservePayment.tsx
  Lotte-Cinema/src/pages/SeatReservation/SeatReservation.tsx
Labels: 🎨 Design, 한서

#57 [Design] 상영관 별 시간 컴포넌트 (시간 선택 뷰)
  Lotte-Cinema/public/svg/ic_arrow_down_20.svg
  Lotte-Cinema/public/svg/ic_arrow_top_20.svg
  Lotte-Cinema/src/assets/svg/IcArrowDown20.tsx
  Lotte-Cinema/src/assets/svg/IcArrowTop20.tsx
  Lotte-Cinema/src/assets/svg/ImgLpayLogo.tsx
  Lotte-Cinema/src/assets/svg/ImgPaymentComplete.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/commons/ArrowBtn.tsx
  Lotte-Cinema/src/components/commons/header/Header.tsx
  Lotte-Cinema/src/components/mainPage/MainPageHeader.tsx
  Lotte-Cinema/src/components/mobileLayout/MobileLayout.tsx
  Lotte-Cinema/src/components/seatReservation/ModalContents.tsx
  Lotte-Cinema/src/components/seatReservation/ModalWrapper.tsx
  Lotte-Cinema/src/components/timeSelect/Calendar.tsx
  Lotte-Cinema/src/components/timeSelect/MovieInfoBar.tsx
  Lotte-Cinema/src/components/timeSelect/TimeInfo.tsx
  Lotte-Cinema/src/components/timeSelect/atom/TheaterLabel.tsx
  Lotte-Cinema/src/components/timeSelect/atom/bar/Button.tsx
  Lotte-Cinema/src/components/timeSelect/atom/bar/CinemaTypeBar.tsx
  Lotte-Cinema/src/components/timeSelect/atom/bar/TimeTypeBar.tsx
  Lotte-Cinema/src/components/timeSelect/atom/bar/index.ts
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/MovieTimeBox.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/TimeAccordion.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/TimeCard.tsx
  Lotte-Cinema/src/components/timeSelect/index.ts
  Lotte-Cinema/src/constants/mocks/cinemaType.ts
  Lotte-Cinema/src/constants/mocks/timeType.ts
  Lotte-Cinema/src/pages/TimeSelect/TimeSelect.tsx
  Lotte-Cinema/src/styles/global.ts
Labels: 🎨 Design, 고은

#59 [Design] 좌석표 구현 (좌석 선택 뷰)
  Lotte-Cinema/package.json
  Lotte-Cinema/public/svg/btn_seat_default_large.svg
  Lotte-Cinema/src/assets/svg/BtnSeatDefaultLarge.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/commons/header/Header.tsx
  Lotte-Cinema/src/components/seatReservation/ModalWrapper.tsx
  Lotte-Cinema/src/components/seatReservation/SeatReserveInfo.tsx
  Lotte-Cinema/src/components/seatReservation/SeatReservePayment.tsx
  Lotte-Cinema/src/components/seatReservation/SeatTableBody.tsx
  Lotte-Cinema/src/constants/index.ts
  Lotte-Cinema/src/constants/seats.ts
  Lotte-Cinema/src/constants/tabs.ts
  Lotte-Cinema/src/pages/SeatReservation/SeatReservation.tsx
Labels: 🎨 Design, 한서

#58 [Design] 메인화면 인기차트 컴포넌트 구현 (메인화면 뷰)
  .DS_Store
  .github/.DS_Store
  Lotte-Cinema/public/svg/ic_arrow_right_gray09_10.svg
  Lotte-Cinema/public/svg/ic_horizontalbar_grey.svg
  Lotte-Cinema/public/svg/ic_star_gray10_10.svg
  Lotte-Cinema/public/svg/img_poster_large_amazon.svg
  Lotte-Cinema/public/svg/img_poster_large_deadline.svg
  Lotte-Cinema/public/svg/img_poster_large_event.svg
  Lotte-Cinema/public/svg/img_poster_large_gladiator.svg
  Lotte-Cinema/public/svg/img_poster_main_aprilcomeshewill.svg
  Lotte-Cinema/src/assets/svg/IcArrowRightGray0910.tsx
  Lotte-Cinema/src/assets/svg/IcHorizontalbarGrey.tsx
  Lotte-Cinema/src/assets/svg/IcStarGray1010.tsx
  Lotte-Cinema/src/assets/svg/IcTicketBlack32.tsx
  Lotte-Cinema/src/assets/svg/ImgLogo.tsx
  Lotte-Cinema/src/assets/svg/ImgPosterLargeAmazon.tsx
  Lotte-Cinema/src/assets/svg/ImgPosterLargeDeadline.tsx
  Lotte-Cinema/src/assets/svg/ImgPosterLargeEvent.tsx
  Lotte-Cinema/src/assets/svg/ImgPosterLargeGladiator.tsx
  Lotte-Cinema/src/assets/svg/ImgPosterMainAprilcomeshewill.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/commons/EntireClickButton.tsx
  Lotte-Cinema/src/components/commons/header/Header.tsx
  Lotte-Cinema/src/components/mainPage/MainImage.tsx
  Lotte-Cinema/src/components/mainPage/MainPageHeader.tsx
  Lotte-Cinema/src/components/mainPage/PopularMovieChart.tsx
  Lotte-Cinema/src/components/mainPage/StylesPopularMovieChart.ts
  Lotte-Cinema/src/components/mobileLayout/MobileLayout.tsx
  Lotte-Cinema/src/constants/PopularMovieChartConstant.tsx
  Lotte-Cinema/src/pages/MainPage/MainPage.tsx
  Lotte-Cinema/src/styles/reset.ts
Labels: 🛠️ Feature, 🎨 Design

#61 Feat/mainpage footer/#30 [Design] 메인화면 하단부 컴포넌트 구현 (메인화면 뷰)
  Lotte-Cinema/public/svg/btn_circle.svg
  Lotte-Cinema/public/svg/ic_arrow_under_gray14_10.svg
  Lotte-Cinema/public/svg/ic_event_black_24.svg
  Lotte-Cinema/public/svg/ic_horizontalbar_10.svg
  Lotte-Cinema/public/svg/ic_menu_black_24.svg
  Lotte-Cinema/public/svg/ic_my_black_24.svg
  Lotte-Cinema/public/svg/ic_ticket_white_24.svg
  Lotte-Cinema/public/svg/ic_time_black_24.svg
  Lotte-Cinema/public/svg/img_banner_full_kblivevent.svg
  Lotte-Cinema/public/svg/img_circle_56.svg
  Lotte-Cinema/src/assets/svg/BtnCircle.tsx
  Lotte-Cinema/src/assets/svg/IcArrowUnderGray1410.tsx
  Lotte-Cinema/src/assets/svg/IcEventBlack24.tsx
  Lotte-Cinema/src/assets/svg/IcHorizontalbar10.tsx
  Lotte-Cinema/src/assets/svg/IcMenuBlack24.tsx
  Lotte-Cinema/src/assets/svg/IcMyBlack24.tsx
  Lotte-Cinema/src/assets/svg/IcTicketWhite24.tsx
  Lotte-Cinema/src/assets/svg/IcTimeBlack24.tsx
  Lotte-Cinema/src/assets/svg/ImgBannerFullKblivevent.tsx
  Lotte-Cinema/src/assets/svg/ImgCircle56.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/mainPage/Footer.tsx
  Lotte-Cinema/src/components/mainPage/MainImage.tsx
  Lotte-Cinema/src/components/mainPage/MainPageHeader.tsx
  Lotte-Cinema/src/components/mainPage/NavFooter.tsx
  Lotte-Cinema/src/components/mobileLayout/MobileLayout.tsx
  Lotte-Cinema/src/pages/MainPage/MainPage.tsx
  Lotte-Cinema/vite.config.ts
Labels: 🎨 Design, 정완

#63 [Design] 롯데시네마 단독 상영 컴포넌트 (메인화면 뷰)
  Lotte-Cinema/public/svg/ic_pic_28_16.svg
  Lotte-Cinema/src/assets/svg/IcPic2816.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/mainPage/ExclusiveChart.tsx
  Lotte-Cinema/src/components/mainPage/Footer.tsx
  Lotte-Cinema/src/components/mainPage/MainImage.tsx
  Lotte-Cinema/src/components/mainPage/MainPageHeader.tsx
  Lotte-Cinema/src/components/mainPage/PopularMovieChart.tsx
  Lotte-Cinema/src/constants/mocks/exclusiveMovie.ts
  Lotte-Cinema/src/constants/mocks/popularMovie.ts
  Lotte-Cinema/src/pages/MainPage/MainPage.tsx
Labels: 🎨 Design, 정완

#65 [Deploy] vercel.json 설정
  Lotte-Cinema/vercel.json
Labels: 🌈 Deploy, 고은

#62 [Feat] 달력 컴포넌트 (시간 선택뷰)
  Lotte-Cinema/package.json
  Lotte-Cinema/src/components/timeSelect/Calendar.tsx
  Lotte-Cinema/src/components/timeSelect/index.ts
  Lotte-Cinema/src/hooks/useCalendar.ts
  Lotte-Cinema/src/pages/TimeSelect/TimeSelect.tsx
  Lotte-Cinema/src/utils/.gitkeep
  Lotte-Cinema/src/utils/calendarUtils.ts
  Lotte-Cinema/yarn.lock
Labels: 🛠️ Feature, 🎨 Design, 고은

#69 [Design] 스크롤 영역 React-slick 캐러셀 구현 (메인화면 뷰)
  Lotte-Cinema/package.json
  Lotte-Cinema/src/components/commons/EntireClickButton.tsx
  Lotte-Cinema/src/components/mainPage/EventAdvertising.tsx
  Lotte-Cinema/src/components/mainPage/ExclusiveChart.tsx
  Lotte-Cinema/src/components/mainPage/Footer.tsx
  Lotte-Cinema/src/components/mainPage/MainPageHeader.tsx
  Lotte-Cinema/src/components/mainPage/NavFooter.tsx
  Lotte-Cinema/src/components/mainPage/StylesPopularMovieChart.ts
  Lotte-Cinema/yarn.lock
Labels: 🎨 Design, 정완

#68 [Feat] 영화 정보 확인 및 인원 선택 페이지 기능 구현 (정보 확인 및 인원 선택 뷰)
  Lotte-Cinema/public/svg/ic_minus_24.svg
  Lotte-Cinema/public/svg/ic_plus_24.svg
  Lotte-Cinema/public/svg/ic_seat_recliner_medium.svg
  Lotte-Cinema/public/svg/ic_seat_soldout_medium.svg
  Lotte-Cinema/public/svg/img_seats_check_default.svg
  Lotte-Cinema/src/assets/svg/IcMinus24.tsx
  Lotte-Cinema/src/assets/svg/IcPlus24.tsx
  Lotte-Cinema/src/assets/svg/IcSeatReclinerMedium.tsx
  Lotte-Cinema/src/assets/svg/IcSeatSoldoutMedium.tsx
  Lotte-Cinema/src/assets/svg/ImgLpayLogo.tsx
  Lotte-Cinema/src/assets/svg/ImgPaymentComplete.tsx
  Lotte-Cinema/src/assets/svg/ImgSeatsCheckDefault.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/InfoCheck/AgeInfo.tsx
  Lotte-Cinema/src/components/InfoCheck/NextButton.tsx
  Lotte-Cinema/src/components/InfoCheck/SeatInfo.tsx
  Lotte-Cinema/src/components/InfoCheck/SeatNumSelect.tsx
  Lotte-Cinema/src/constants/mocks/availableIdxData.ts
  Lotte-Cinema/src/constants/mocks/userTypes.ts
  Lotte-Cinema/src/pages/InfoCheck/InfoCheck.tsx
  Lotte-Cinema/src/types/infoCheckType.ts
Labels: 🛠️ Feature, 🎨 Design, 진혁

#66 [Feat] 좌석 선택 기능 구현
  Lotte-Cinema/public/svg/btn_seat_disabled_large.svg
  Lotte-Cinema/src/assets/svg/BtnSeatDefaultLarge.tsx
  Lotte-Cinema/src/assets/svg/BtnSeatDisabledLarge.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/seatReservation/ModalWrapper.tsx
  Lotte-Cinema/src/components/seatReservation/SeatReserveInfo.tsx
  Lotte-Cinema/src/components/seatReservation/SeatReservePayment.tsx
  Lotte-Cinema/src/components/seatReservation/SeatTableBody.tsx
  Lotte-Cinema/src/pages/SeatReservation/SeatReservation.tsx
Labels: 🛠️ Feature, 한서

#78 [Feat] 인기 상영작 / 단독 상영작 API 생성 및 END_POINT 상수처리
  Lotte-Cinema/src/apis/axiosInstance.ts
  Lotte-Cinema/src/apis/movie/getExclusiveList.ts
  Lotte-Cinema/src/apis/movie/getPopularList.ts
  Lotte-Cinema/src/apis/movie/index.ts
  Lotte-Cinema/src/components/timeSelect/MovieInfoBar.tsx
  Lotte-Cinema/src/constants/api.ts
Labels: 🛠️ Feature

#73 [Feat] 영화관 지역 선택 기능 구현 (영화관 선택 뷰)
  Lotte-Cinema/public/svg/ic_check_red_20.svg
  Lotte-Cinema/src/assets/svg/IcCheckRed20.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/TheaterList/List.tsx
  Lotte-Cinema/src/components/TheaterList/Pin.tsx
  Lotte-Cinema/src/components/TheaterList/SelectActions.tsx
  Lotte-Cinema/src/components/TheaterList/SelectButton.tsx
  Lotte-Cinema/src/constants/mocks/theaterRegion.ts
  Lotte-Cinema/src/pages/TheaterList/TheaterList.tsx
  Lotte-Cinema/src/styles/typographies.ts
Labels: 🛠️ Feature, 🎨 Design, 🔧 Fix, 진혁

#81 [Feat] 좌석 선택 뷰 API 연결
  Lotte-Cinema/public/svg/btn_seat_soldout_large.svg
  Lotte-Cinema/src/apis/seatReservation/index.ts
  Lotte-Cinema/src/assets/svg/BtnSeatSoldoutLarge.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/seatReservation/SeatReserveInfo.tsx
  Lotte-Cinema/src/components/seatReservation/SeatReservePayment.tsx
  Lotte-Cinema/src/components/seatReservation/SeatTableBody.tsx
  Lotte-Cinema/src/constants/api.ts
  Lotte-Cinema/src/hooks/query/.gitkeep
  Lotte-Cinema/src/hooks/query/SeatReservation.ts
  Lotte-Cinema/src/hooks/queryClient.ts
  Lotte-Cinema/src/types/data.ts
Labels: 🛠️ Feature, 한서

#82 [Feat] 좌석 정보 조회 API 연결
  Lotte-Cinema/src/components/InfoCheck/NextButton.tsx
  Lotte-Cinema/src/components/InfoCheck/SeatInfo.tsx
  Lotte-Cinema/src/components/InfoCheck/SeatNumSelect.tsx
  Lotte-Cinema/src/components/TheaterList/SelectButton.tsx
  Lotte-Cinema/src/pages/InfoCheck/InfoCheck.tsx
  Lotte-Cinema/src/pages/SeatReservation/SeatReservation.tsx
  Lotte-Cinema/src/types/data.ts
Labels: 🛠️ Feature

#83 [Feat] : 상영 시간 선택 VIEW API 연결
  Lotte-Cinema/package.json
  Lotte-Cinema/src/apis/movie/getExclusiveList.ts
  Lotte-Cinema/src/apis/movie/getMovieTime.ts
  Lotte-Cinema/src/apis/movie/getPopularList.ts
  Lotte-Cinema/src/apis/movie/index.ts
  Lotte-Cinema/src/components/timeSelect/Calendar.tsx
  Lotte-Cinema/src/components/timeSelect/MovieInfoBar.tsx
  Lotte-Cinema/src/components/timeSelect/TimeInfo.tsx
  Lotte-Cinema/src/components/timeSelect/atom/TheaterLabel.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/MovieTimeBox.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/TimeAccordion.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/TimeCard.tsx
  Lotte-Cinema/src/constants/api.ts
  Lotte-Cinema/src/hooks/query/index.ts
  Lotte-Cinema/src/hooks/query/useMovieListQuery.ts
  Lotte-Cinema/src/hooks/query/useMovieTime.ts
  Lotte-Cinema/src/pages/TimeSelect/TimeSelect.tsx
  Lotte-Cinema/yarn.lock
Labels: 🛠️ Feature

#85 [Refactor] 상영관 시간 선택 VIEW
  Lotte-Cinema/src/components/timeSelect/Calendar.tsx
  Lotte-Cinema/src/components/timeSelect/MovieInfoBar.tsx
  Lotte-Cinema/src/components/timeSelect/TimeInfo.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/MovieTimeBox.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/TimeAccordion.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/TimeCard.tsx
  Lotte-Cinema/src/hooks/query/index.ts
  Lotte-Cinema/src/hooks/query/useMovieListQuery.ts
  Lotte-Cinema/src/hooks/query/useMovieTime.ts
  Lotte-Cinema/src/hooks/timeSelect/index.ts
  Lotte-Cinema/src/hooks/timeSelect/useCalendar.ts
  Lotte-Cinema/src/hooks/timeSelect/useDateLocSelect.ts
  Lotte-Cinema/src/hooks/timeSelect/useMovieSelect.ts
  Lotte-Cinema/src/pages/TimeSelect/TimeSelect.tsx
  Lotte-Cinema/src/types/data.ts
  Lotte-Cinema/src/types/timeSelect/index.ts
Labels: 🪄 Refactor

#88 [Feat] 진혁이 뷰랑 연결, 스크롤 중앙 초기화 오류 해결 (좌석 선택 뷰)
  Lotte-Cinema/src/components/seatReservation/SeatReserveInfo.tsx
  Lotte-Cinema/src/components/seatReservation/SeatReservePayment.tsx
  Lotte-Cinema/src/components/seatReservation/SeatTableBody.tsx
  Lotte-Cinema/src/pages/SeatReservation/SeatReservation.tsx
  Lotte-Cinema/src/styles/reset.ts
Labels: 🛠️ Feature, 한서

#93 [Feat] 정보 확인 페이지 state 연결
  Lotte-Cinema/src/components/InfoCheck/AgeInfo.tsx
  Lotte-Cinema/src/components/InfoCheck/MovieInfoBanner.tsx
  Lotte-Cinema/src/components/InfoCheck/TimeInfoList.tsx
  Lotte-Cinema/src/components/TheaterList/SelectActions.tsx
  Lotte-Cinema/src/components/timeSelect/MovieInfoBar.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/TimeAccordion.tsx
  Lotte-Cinema/src/components/timeSelect/atom/infoBox/TimeCard.tsx
  Lotte-Cinema/src/hooks/infoCheck/useGetAgeInfo.tsx
  Lotte-Cinema/src/hooks/timeSelect/useCalendar.ts
  Lotte-Cinema/src/hooks/timeSelect/useDateLocSelect.ts
  Lotte-Cinema/src/pages/InfoCheck/InfoCheck.tsx
  Lotte-Cinema/src/pages/TheaterList/TheaterList.tsx
  Lotte-Cinema/src/types/infoCheck/index.ts
  Lotte-Cinema/src/utils/calculateMovieInfo.ts
Labels: 🛠️ Feature, 진혁

#95 [Feat] 영화정보 연결
  Lotte-Cinema/src/components/seatReservation/SeatReserveInfo.tsx
  Lotte-Cinema/src/pages/SeatReservation/SeatReservation.tsx
Labels: 🛠️ Feature, 한서

#100 [Design] favicon 추가
  Lotte-Cinema/index.html
Labels: 🎨 Design

#101 [Fix] 좌석 정보 쿼리 동적 값으로 변경
  Lotte-Cinema/src/components/InfoCheck/SeatInfo.tsx
  Lotte-Cinema/src/pages/InfoCheck/InfoCheck.tsx
Labels: 🔧 Fix

#119 [Fix] 모바일 레이아웃 조건부 overflow 처리 및 오타 수정
  Lotte-Cinema/src/components/mobileLayout/MobileLayout.tsx
Labels: 🔧 Fix

#122 [feat] 미니맵 좌석 구현
  Lotte-Cinema/public/svg/ic_seat_default_small.svg
  Lotte-Cinema/public/svg/ic_seat_selected_small.svg
  Lotte-Cinema/src/assets/svg/IcSeatDefaultSmall.tsx
  Lotte-Cinema/src/assets/svg/IcSeatSelectedSmall.tsx
  Lotte-Cinema/src/assets/svg/index.ts
  Lotte-Cinema/src/components/seatReservation/MiniMap.tsx
Labels: 🛠️ Feature, 🎨 Design, 한서
